
$(document).ready(function(){
    $("#libro1").click(function(){
      $(this).hide()
      $("#libro1reservado").show()
    })
    $("#libro1reservado").click(function(){
        $(this).hide()
        $("#libro1").show()
      })
    $("#libro2").click(function(){
      $(this).hide()
      $("#libro2reservado").show()
    })
    $("#libro2reservado").click(function(){
        $(this).hide()
        $("#libro2").show()
      })
    $("#libro3").click(function(){
      $(this).hide()
      $("#libro3reservado").show()
    })
    $("#libro3reservado").click(function(){
        $(this).hide()
        $("#libro3").show()
      })
    $("#libro4").click(function(){
      $(this).hide()
      $("#libro4reservado").show()
    })
    $("#libro4reservado").click(function(){
        $(this).hide()
        $("#libro4").show()
      })
        $("#libro2").click(function(){
      $(this).hide()
      $("#libro2reservado").show()
    })
    $("#libro2reservado").click(function(){
        $(this).hide()
        $("#libro2").show()
      })
    $("#libro3").click(function(){
      $(this).hide()
      $("#libro3reservado").show()
    })
    $("#libro3reservado").click(function(){
        $(this).hide()
        $("#libro3").show()
      })
    $("#libro4").click(function(){
      $(this).hide()
      $("#libro4reservado").show()
    })
    $("#libro4reservado").click(function(){
        $(this).hide()
        $("#libro4").show()
      })
    $("#libro5").click(function(){
      $(this).hide()
      $("#libro5reservado").show()
    })
    $("#libro5reservado").click(function(){
        $(this).hide()
        $("#libro5").show()
      })
    $("#libro6").click(function(){
      $(this).hide()
      $("#libro6reservado").show()
    })
    $("#libro6reservado").click(function(){
        $(this).hide()
        $("#libro6").show()
      })
    $("#libro7").click(function(){
      $(this).hide()
      $("#libro7reservado").show()
    })
    $("#libro7reservado").click(function(){
        $(this).hide()
        $("#libro7").show()
      })
    


})
